baseurl = "https://jrzimmerman.github.io/"
languageCode = "en-us"
title = "Justin Zimmerman"
disqusShortname = "jrzimmerman"

theme = "hyde"
[params]
  themeColor = "theme-base-0d"

[Author]
  name = "Justin Zimmerman"
