baseurl = "https://jrzimmerman.github.io/"
languageCode = "en-us"
title = "Justin Zimmerman"
disqusShortname = "jrzimmerman"
copyright = "Justin Zimmerman"
theme = "hyde"

[Author]
  name = "Justin Zimmerman"

[params]
  themeColor = "theme-base-0d"
  github = "https://github.com/jrzimmerman"
  twitter = "https://twitter.com/justzimmerman"