baseurl = "https://jrzimmerman.github.io/"
languageCode = "en-us"
title = "Justin Zimmerman"
copyright = "Justin Zimmerman"
theme = "hyde-y"
googleAnalytics = "UA-37904415-1"

[Author]
  name = "Justin Zimmerman"

[params]
  description = "Full Stack Software Engineer"
  themeColor = "theme-base-0d"
  github = "https://github.com/jrzimmerman"
  twitter = "https://twitter.com/justzimmerman"
  linkedin = "https://www.linkedin.com/in/justinrzimmerman"
  disqusShortname = "justinzimmerman"